name: login
on:
  workflow_dispatch:
  # push:
  # schedule:
  #   - cron: 1 16 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run login
        env:
          PHONES: ${{ secrets.PHONES }}
          KEYS: ${{ secrets.KEYS }}
      # 上传登录结果作为artifacts
      - name: login-results
        uses: actions/upload-artifact@v4
        with:
          retention-days: 70
          name: login-results
          path: ./login_res.json