name: QRcode
on:
  workflow_dispatch:
  # push:
  # schedule:
  #   - cron: 1 16 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run qrcode
        env:
          SIZE: ${{ secrets.SIZE }}
      # 上传结果文件作为artifact
      - name: qrcode-results
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: qrcode-results
          path: ./qr-res.json
      - name: Upload QR Code Images
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: qrcode-images
          path: ./qr-codes.html