name: QRcode
on:
  workflow_dispatch:
  # push:
  # schedule:
  #   - cron: 1 16 * * *
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm run install
      - run: npm run qrcode
        env:
          SIZE: ${{ secrets.SIZE }}
      # 上传结果文件作为artifact
      - name: Upload QR Code Results
        uses: actions/upload-artifact@v4
        with:
          name: qrcode-results
          path: ./qr_res.json